---
abstract: 'ZMQ backend for Log::Dispatch'
author:
  - 'Tomasz Czepiel <tjmc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-ZMQ
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Log::Dispatch: 0
  Test::SharedFork: 0
  ZMQ: 0
  parent: 0
resources:
  repository: git://github.com/tczepiel/perl-log-dispatch-zmq.git
version: 0.02
